# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volt', '0008_auto_20190520_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voltservice_decl',
            name='onos_voltha_pass',
        ),
        migrations.RemoveField(
            model_name='voltservice_decl',
            name='onos_voltha_port',
        ),
        migrations.RemoveField(
            model_name='voltservice_decl',
            name='onos_voltha_url',
        ),
        migrations.RemoveField(
            model_name='voltservice_decl',
            name='onos_voltha_user',
        ),
    ]
